{{ 
  config(
    materialized='table'
  ) 
}}

WITH date_range AS (
    SELECT 
        DATEADD(DAY, SEQ4(), DATEADD(YEAR, -3, CURRENT_DATE())) AS DATE_KEY
    FROM TABLE(GENERATOR(ROWCOUNT => 1461))  -- 3 years + 1 year = 4 years ≈ 1461 days
)
SELECT
    DATE_KEY,
    EXTRACT(YEAR FROM DATE_KEY) AS YEAR,
    EXTRACT(MONTH FROM DATE_KEY) AS MONTH,
    EXTRACT(DAY FROM DATE_KEY) AS DAY,
    EXTRACT(DAYOFWEEK FROM DATE_KEY) AS DAY_OF_WEEK,
    CASE WHEN EXTRACT(DAYOFWEEK FROM DATE_KEY) IN (1, 7) THEN 1 ELSE 0 END AS IS_WEEKEND,
    DATE_TRUNC('WEEK', DATE_KEY) AS WEEK_START_DATE,
    DATE_TRUNC('MONTH', DATE_KEY) AS MONTH_START_DATE,
    DATE_TRUNC('QUARTER', DATE_KEY) AS QUARTER_START_DATE,
    DATE_TRUNC('YEAR', DATE_KEY) AS YEAR_START_DATE,
    TO_CHAR(DATE_KEY, 'Day') AS DAY_NAME,
    TO_CHAR(DATE_KEY, 'Month') AS MONTH_NAME
FROM date_range
WHERE DATE_KEY <= DATEADD(YEAR, 1, CURRENT_DATE())
ORDER BY DATE_KEY