version: 2

sources:
  - name: src_inventory
    description: ""
    database: dbt_dev
    schema: sch_bronze_inventory
    tables:
      - name: inventory_levels
        description: ""
      - name: inventory_transactions
        description: ""