{{ 
config(
    tags = ['sales']
) 
}}

SELECT
  CUSTOMER_ID,
  ADDRESS_ID,
  TRIM(ADDRESS_LINE1) AS ADDRESS_LINE1,
  TRIM(CITY) AS CITY,
  UPPER(TRIM(STATE)) AS STATE,
  TRIM(POSTAL_CODE) AS POSTAL_CODE,
  UPPER(TRIM(COUNTRY)) AS COUNTRY,
  UPPER(TRIM(ADDRESS_TYPE)) AS ADDRESS_TYPE
FROM {{ ref('stg_salesdb__addresses') }}